spring.application.name=leadScope

springdoc.swagger-ui.path=/leads-doc
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.defaultModelsExpandDepth=-1

spring.mongodb.uri=mongodb+srv://pioriam:Ru1p%401xe5@cnpja.wotg5cj.mongodb.net/n8n?retryWrites=true&w=majority
server.port=${PORT:8080}




cnpja.url = https://api.cnpja.com
cnpja.token=c4120aab-3b5e-4f92-9f65-ff534e249f8c-c3861677-251c-4c1b-a19d-04120d9c39a2





